[package]
name = "du-dust"
description = "A more intuitive version of du"
version = "0.2.4"
authors = ["bootandy <bootandy@gmail.com>", "nebkor <code@ardent.nebcorp.com>"]

documentation = "https://github.com/bootandy/dust"
homepage = "https://github.com/bootandy/dust"
repository = "https://github.com/bootandy/dust"

keywords = ["du", "command-line", "disk", "disk-usage"]
categories = ["command-line-utilities"]
license = "Apache-2.0"

[badges]
travis-ci = {repository = "https://travis-ci.org/bootandy/dust"}

[[bin]]
name = "dust"
path = "src/main.rs"

[dependencies]
ansi_term = "0.11"
clap = "2.31"
assert_cli = "0.5"
tempfile = "3"
ignore = "0.3"

